### PR TITLE
Add optional separator argument

### PR DESCRIPTION
**Pull request by sdht0**
I made the following updates:
* An optional separator char can be specified, when the input file is comma separated for example.
* Remove dedup by default.
* Added useful output messages.
* Updated the library dependencies.

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Thanks! 

This seems good. I think you have reduced the functionality by removing the sort option, as it could previously be interleaved among other commands (e.g, "sort, dedup, undirect" followed by the final sort, dedup). If you aren't strongly attached to that, or have a clear argument for why it isn't actually a reduction, I'm otherwise ok with this!

**Comment by sdht0** [comment]
Ah I see. My reasoning was that a sort is always performed, and selecting the "sort" option naively performs the sort twice.

**Comment by frankmcsherry** [comment]
Ooo, and reading a bit more, it looks like the `dedup` variable might be erroneously set if you do a dedup followed by an undirect or randomize, as they could turn `(a, b)`, `(b, a)` into duplicates.

**Comment by sdht0** [comment]
And that is why we have code reviews :)
In the normal case, dedup without a sort will not work as expected.

**Review by frankmcsherry — APPROVED** [review]
Looks good to me! There (I think) is a minor behavior change that there is no implicit dedup at the end, and anyone who wants that should put a `dedup` as their last command. It looks like the code is correct even with duplicate edges, like in the final extraction stages, but I did want to mention it! I'm 100% fine with it.

**Comment by sdht0** [comment]
Thanks! I do think making the dedup explicit is a good idea.

**Pull request merged**
